volumes:
  jenkins-data:
  jenkins-docker-certs:

services:
  jenkins-blueocean:
    build: 
      context: ./jenkins
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    env_file:
      # relative path of env variables
      - ./config/jenkins.env 
    restart: on-failure